<?php

use Illuminate\Database\Seeder;

class GeneratedurlsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('generatedurls')->delete();

        \DB::table('generatedurls')->insert(array (
            0 =>
            array (
                'id' => 41,
                'operator_id' => 12,
                'occasion_id' => 40,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 590141,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-09-23 15:26:08',
                'updated_at' => '2015-09-23 15:26:08',
            ),
            1 =>
            array (
                'id' => 46,
                'operator_id' => 8,
                'occasion_id' => 24,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 220346,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-10-01 13:36:02',
                'updated_at' => '2015-10-01 13:36:02',
            ),
            2 =>
            array (
                'id' => 47,
                'operator_id' => 8,
                'occasion_id' => 8,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 775647,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-10-08 10:30:07',
                'updated_at' => '2015-10-08 10:30:07',
            ),
            3 =>
            array (
                'id' => 48,
                'operator_id' => 8,
                'occasion_id' => 26,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 833448,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-10-08 10:31:45',
                'updated_at' => '2015-10-08 10:31:45',
            ),
            4 =>
            array (
                'id' => 49,
                'operator_id' => 8,
                'occasion_id' => 31,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 121049,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-10-13 12:58:36',
                'updated_at' => '2015-10-13 12:58:36',
            ),
            5 =>
            array (
                'id' => 50,
                'operator_id' => 8,
                'occasion_id' => 30,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 183450,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-10-18 09:41:24',
                'updated_at' => '2015-10-18 09:41:24',
            ),
            6 =>
            array (
                'id' => 51,
                'operator_id' => 8,
                'occasion_id' => 26,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 527851,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-01 11:23:42',
                'updated_at' => '2015-11-01 11:23:42',
            ),
            7 =>
            array (
                'id' => 52,
                'operator_id' => 8,
                'occasion_id' => 42,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 596052,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-22 16:41:43',
                'updated_at' => '2015-11-22 16:41:43',
            ),
            8 =>
            array (
                'id' => 53,
                'operator_id' => 8,
                'occasion_id' => 32,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 957453,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 14:16:36',
                'updated_at' => '2015-11-23 14:16:36',
            ),
            9 =>
            array (
                'id' => 54,
                'operator_id' => 22,
                'occasion_id' => 42,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 150254,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 14:53:21',
                'updated_at' => '2015-11-23 14:53:21',
            ),
            10 =>
            array (
                'id' => 55,
                'operator_id' => 22,
                'occasion_id' => 44,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 800255,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 14:58:19',
                'updated_at' => '2015-11-23 14:58:19',
            ),
            11 =>
            array (
                'id' => 56,
                'operator_id' => 22,
                'occasion_id' => 32,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 918156,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 15:01:29',
                'updated_at' => '2015-11-23 15:01:29',
            ),
            12 =>
            array (
                'id' => 57,
                'operator_id' => 22,
                'occasion_id' => 43,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 899957,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 15:02:10',
                'updated_at' => '2015-11-23 15:02:10',
            ),
            13 =>
            array (
                'id' => 58,
                'operator_id' => 22,
                'occasion_id' => 37,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 108058,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 15:02:56',
                'updated_at' => '2015-11-23 15:02:56',
            ),
            14 =>
            array (
                'id' => 59,
                'operator_id' => 22,
                'occasion_id' => 21,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 728159,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 15:10:10',
                'updated_at' => '2015-11-23 15:10:10',
            ),
            15 =>
            array (
                'id' => 60,
                'operator_id' => 22,
                'occasion_id' => 41,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 842060,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 15:10:43',
                'updated_at' => '2015-11-23 15:10:43',
            ),
            16 =>
            array (
                'id' => 61,
                'operator_id' => 22,
                'occasion_id' => 40,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 768661,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 15:11:24',
                'updated_at' => '2015-11-23 15:11:24',
            ),
            17 =>
            array (
                'id' => 62,
                'operator_id' => 22,
                'occasion_id' => 30,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 788762,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-23 15:12:12',
                'updated_at' => '2015-11-23 15:12:12',
            ),
            18 =>
            array (
                'id' => 63,
                'operator_id' => 8,
                'occasion_id' => 21,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 332863,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-11-29 12:09:49',
                'updated_at' => '2015-11-29 12:09:49',
            ),
            19 =>
            array (
                'id' => 64,
                'operator_id' => 8,
                'occasion_id' => 5,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 640064,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-12-22 11:09:07',
                'updated_at' => '2015-12-22 11:09:07',
            ),
            20 =>
            array (
                'id' => 65,
                'operator_id' => 8,
                'occasion_id' => 44,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 742865,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2015-12-23 18:08:19',
                'updated_at' => '2015-12-23 18:08:19',
            ),
            21 =>
            array (
                'id' => 66,
                'operator_id' => 8,
                'occasion_id' => 19,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 222366,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2016-02-01 15:20:00',
                'updated_at' => '2016-02-01 15:20:00',
            ),
            22 =>
            array (
                'id' => 67,
                'operator_id' => 8,
                'occasion_id' => 19,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 854167,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2016-02-07 15:15:16',
                'updated_at' => '2016-02-07 15:15:16',
            ),
            23 =>
            array (
                'id' => 68,
                'operator_id' => 8,
                'occasion_id' => 18,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 406468,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2016-02-07 16:23:07',
                'updated_at' => '2016-02-07 16:23:07',
            ),
            24 =>
            array (
                'id' => 69,
                'operator_id' => 22,
                'occasion_id' => 44,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 326869,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2016-02-18 13:09:04',
                'updated_at' => '2016-02-18 13:09:04',
            ),
            25 =>
            array (
                'id' => 70,
                'operator_id' => 17,
                'occasion_id' => 46,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 112470,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2016-02-22 14:03:30',
                'updated_at' => '2016-02-22 14:03:30',
            ),
            26 =>
            array (
                'id' => 73,
                'operator_id' => 17,
                'occasion_id' => 47,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 931073,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2016-02-22 15:19:36',
                'updated_at' => '2016-02-22 15:19:36',
            ),
            27 =>
            array (
                'id' => 74,
                'operator_id' => 8,
                'occasion_id' => 6,
                'img' => 0,
                'audio' => 0,
                'video' => 1,
                'UID' => 603074,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2017-01-30 14:11:40',
                'updated_at' => '2017-01-30 14:11:40',
            ),
            28 =>
            array (
                'id' => 75,
                'operator_id' => 8,
                'occasion_id' => 6,
                'img' => 0,
                'audio' => 0,
                'video' => 1,
                'UID' => 715775,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2017-01-31 15:17:54',
                'updated_at' => '2017-01-31 15:17:54',
            ),
            29 =>
            array (
                'id' => 76,
                'operator_id' => 8,
                'occasion_id' => 6,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 348376,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2017-01-31 16:00:00',
                'updated_at' => '2017-01-31 16:00:00',
            ),
            30 =>
            array (
                'id' => 77,
                'operator_id' => 17,
                'occasion_id' => 29,
                'img' => 1,
                'audio' => 0,
                'video' => 0,
                'UID' => 392177,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2018-06-06 09:50:43',
                'updated_at' => '2018-06-06 09:50:43',
            ),
            31 =>
            array (
                'id' => 78,
                'operator_id' => 17,
                'occasion_id' => 29,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 661078,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2018-06-06 10:46:21',
                'updated_at' => '2018-06-06 10:46:21',
            ),
            32 =>
            array (
                'id' => 79,
                'operator_id' => 17,
                'occasion_id' => 29,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 237179,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2018-06-06 11:18:38',
                'updated_at' => '2018-06-06 11:18:39',
            ),
            33 =>
            array (
                'id' => 80,
                'operator_id' => 17,
                'occasion_id' => 29,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 283580,
                'url_occasion_text' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

',
                'url_occasion_image' => NULL,
                'created_at' => '2018-06-06 11:20:11',
                'updated_at' => '2018-06-06 11:20:11',
            ),
            34 =>
            array (
                'id' => 81,
                'operator_id' => 17,
                'occasion_id' => 29,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 352981,
                'url_occasion_text' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

',
                'url_occasion_image' => 'Greetings/url/1528360037.jpg',
                'created_at' => '2018-06-06 11:21:01',
                'updated_at' => '2018-06-07 08:27:17',
            ),
            35 =>
            array (
                'id' => 82,
                'operator_id' => 17,
                'occasion_id' => 29,
                'img' => 0,
                'audio' => 0,
                'video' => 1,
                'UID' => 421182,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2018-06-06 11:23:48',
                'updated_at' => '2018-06-06 12:06:12',
            ),
            36 =>
            array (
                'id' => 83,
                'operator_id' => 17,
                'occasion_id' => 29,
                'img' => 0,
                'audio' => 0,
                'video' => 1,
                'UID' => 745183,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2018-06-07 08:35:25',
                'updated_at' => '2018-06-07 08:36:51',
            ),
            37 =>
            array (
                'id' => 84,
                'operator_id' => 17,
                'occasion_id' => 29,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 815984,
                'url_occasion_text' => 'كل عام وانت بخير',
                'url_occasion_image' => 'Greetings/url/1528360685.jpeg',
                'created_at' => '2018-06-07 08:38:05',
                'updated_at' => '2018-06-07 09:25:38',
            ),
            38 =>
            array (
                'id' => 85,
                'operator_id' => 8,
                'occasion_id' => 5,
                'img' => 1,
                'audio' => 0,
                'video' => 1,
                'UID' => 754085,
                'url_occasion_text' => NULL,
                'url_occasion_image' => NULL,
                'created_at' => '2018-08-14 09:08:10',
                'updated_at' => '2018-08-15 14:10:42',
            ),
        ));


    }
}
