@extends('greeting.master')
@section('form')
    <!--<form id="greetingForm">-->
    {!! Form::open(['id'=>'greetingForm','action'=>'FrontEndController@processVideo','method' => 'get']) !!}
    <!-- progress bar -->
    <div>
        {{--@if($errors->any())
            <ul class="alert-box warning round">
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        @endif--}}
    </div>
    <!--<ul id="progressbar" class="cf">
        <li class="active">المناسبة</li>
        <li>المؤدي</li>
        <li>الاسم</li>
    </ul>-->

    <!-- fieldsets -->

    <fieldset id="picture">
        <div>
            <div class="fieldset-wrapper">
                @if($errors->any())

                    <div class="errors">
                        <i class="fa fa-times"></i>
                        <ul class="alert-box warning round">
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                {!! Form::label('occasion_id','اختر المناسبة') !!}

                <div class="select-panel">
                    {!! Form::select('occasion_id',$occasions,$default,['id'=>'chooseOccasion','data-url'=>url('images')]) !!}
                    <i class="fa fa-angle-down"></i>
                </div>

                <!-- hidden input for operator_id -->
                {!! Form::hidden('operator_id',$url->operator_id,['id'=>'operator_id'])!!}

                <!-- the options are generated by script-->
                {!! Form::label('choosePicture','اختر الصورة') !!}
                <div id="thumbnails-container" class="cf">
                    <select id="choosePicture" name="image" class="image-picker ajax-select">
                        @include('greeting._chooseImg')
                    </select>
                </div>
            </div>
        </div>

        <div class="fieldset-controls">
            <input  id="continue" type="hidden" name="next" class="next action-button ajax-select no-float" value="استمرار" />

        </div>

    </fieldset>

    <fieldset id="audio">
        <div>
            <div class="fieldset-wrapper">
                {!! Form::label('chooseProvider','اختر المؤدي') !!}

                <!-- select generated by laravel-->
                <div class="select-panel">
                    <select id="chooseProvider" name="provider"  class="ajax-select" data-url="{{ url('vidoes') }}">
                        @include('greeting._chooseProv')
                    </select>
                    <i class="fa fa-angle-down"></i>
                </div>


                <!-- the options are generated by script-->
                {!! Form::label('chooseAudio','اختر الصوت') !!}

                <div id="chooseAudio">
                    @include('greeting._greetingAudios')
                </div>



            </div>
        </div>

        <div class="fieldset-controls">
            <input type="hidden" name="previous" class="previous" value="رجوع" />
            <input   type="hidden"   name="next" id="audio_next" class="next" value="استمرار" />
        </div>
    </fieldset>

    <fieldset id="enterName">
        <div>
            <div class="fieldset-wrapper">
                <span class="input input--nariko">
                    <input class="input__field input__field--nariko" required="required" type="text" name="name" id="input-22" />
                    <label class="input__label input__label--nariko" for="input-22">
                        <span class="input__label-content input__label-content--nariko">النص </span>
                    </label>
                </span>

                  <span class="input input--nariko">
                      <input type="submit" style="background: #3067AB !important;color:#fff;;font-family: 'Droid Arabic Kufi', sans-serif !important ;" id="submit" data-img-src="{{asset('img/oval.svg')}}" class="" value="انتهاء"/>

                      </span>


            </div>
        </div>
        <div class="fieldset-controls cf">
            <input type="hidden" name="previous" class="previous" value="رجوع" />
            <input type="hidden" id="submit" data-img-src="{{asset('img/oval.svg')}}" class="submit" value="انتهاء"/>

        </div>
    </fieldset>


    {!! Form::close()!!}
    <!--<div class="clearFooter"></div>-->
@stop
@section('script')
    <script>
        /*$('#audio_next').on('click',function(){
            var player = document.getElementById('player');
            player.pause();
            console.log(player)
            $('.np-play').css({
                "background": "url(img/play_small.svg) no-repeat  center"
            });

        });*/

        $(function(){
            /*
             *  select menu with image options
             */
            $('#choosePicture').imagepicker();

            /*
             *  onchange event on select occasion to load images for occasion
             */
            $('#chooseOccasion').on('change',function(){
                var occasion_id   = $(this).val();
                var operator_id   = $('#operator_id').val();
                var url           = $(this).attr('data-url');


            $('#chooseProvider').change();

                //clear default audios
                $('#chooseAudio').empty();

                // get images with ajax
                $.ajax({
                    type:'GET',
                    url: url,
                    data:{
                        operator_id: operator_id,
                        occasion_id: occasion_id
                    },
                    success:function(result){
                        //console.log(result);
                        //change html of image select with the result images
                        $('#thumbnails-container').html(result);

                        //BUG: call image picker again
                        $('#choosePicture').imagepicker();
                    }
                });

                //get providers for occasion
                $.ajax({
                    type:'GET',
                    url: 'providers',
                    data:{
                        operator_id: operator_id,
                        occasion_id: occasion_id
                    },
                    success:function(result){
                        //console.log(result);
                        //change html of image select with the result images
                        console.log(result);
                        $('#chooseProvider').html(result);
                        $('#chooseProvider').trigger('change');

                      //  var provider_first_value =   $("#chooseProvider").find("option:first-child").val() ;
                        //  alert(provider_first_value);

                     //   $('#choosePicture').val('value').change(provider_first_value);
                     //   $('#choosePicture').val(provider_first_value).trigger('change');



                    }
                });

            });//end change event


            /*
             *  onchange event on select provider to load audios
             */
            $('#chooseProvider').on('change',function(){
                var cprovider_id  = $(this).val();
                var occasion_id   = $('#chooseOccasion').val();
                var operator_id   = $('#operator_id').val();
                var url           = $(this).attr('data-url');



                // send data with ajax
                $.ajax({
                    type:'GET',
                    url: url,
                    data:{
                        operator_id: operator_id,
                        cprovider_id: cprovider_id,
                        occasion_id: occasion_id
                    },
                    success:function(result){
                        //console.log(result);
                        //change audios
                        $('#chooseAudio').html(result);


                    }
                });
            });//end change event

        });//end ready

    </script>
@stop