@extends('greeting.master')
@section('style')
    <style>
        #progressbar {
            width: 80%;
            margin: 15px auto 20px;
        }

        #progressbar li{
            width: 50%;
        }
    </style>
    @stop
    @section('form')
            <!--<form id="greetingForm">-->
    {!! Form::open(['id'=>'greetingForm','action'=>'FrontEndController@processImage','method' => 'get']) !!}
            <!-- progress bar -->

    <!--<ul id="progressbar" class="cf">
        <li class="active">المناسبة</li>
        <li>الاسم</li>
    </ul>-->

    <!-- fieldsets -->
    @if($errors->any())

        <div class="errors">
            <i class="fa fa-times"></i>
            <ul class="alert-box warning round">
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <fieldset id="picture">
        <div>
            <div class="fieldset-wrapper">


                <!-- hidden input for operator_id -->
                {!! Form::hidden('operator_id',$url->operator_id,['id'=>'operator_id'])!!}

                {!! Form::hidden('occasion_id',$default,['id'=>'occasion_id'])!!}

                        <!-- the options are generated by script-->
                {!! Form::label('choosePicture','اختر الصورة') !!}

                <div id="thumbnails-container" class="cf">

                    <select id="choosePicture" name="image" class="image-picker ajax-select">
                        @include('greeting._chooseImg')
                    </select>

                </div>
            </div>

            <div class="fieldset-controls">
                <input type="button" name="next" class="next action-button ajax-select no-float" value="استمرار" />

            </div>
        </div>


    </fieldset>


    <fieldset id="enterName">
        <div>
            <div class="fieldset-wrapper">
                <span class="input input--nariko">
                    <input class="input__field input__field--nariko" type="text" name="name" id="input-22" />
                    <label class="input__label input__label--nariko" for="input-22">
                        <span class="input__label-content input__label-content--nariko">اكتب الاسم</span>
                    </label>
                </span>
            </div>

            <div class="fieldset-controls cf">
                <input type="button" name="previous" class="previous action-button" value="رجوع" />
                <input type="submit" id="submit" data-img-src="{{asset('img/oval.svg')}}" class="submit" value="انتهاء"/>

            </div>
        </div>

    </fieldset>


    {!! Form::close()!!}
            <!--<div class="clearFooter"></div>-->
@stop
@section('script')
    <script>

        $(function(){
            /*
             *  select menu with image options
             */
            $('#choosePicture').imagepicker();

            /*
             *  onchange event on select occasion to load images for occasion
             */
            $('#chooseOccasion').on('change',function(){
                var occasion_id   = $(this).val();
                var operator_id   = $('#operator_id').val();
                var url           = $(this).attr('data-url');

                // send data with ajax
                $.ajax({
                    type:'GET',
                    url: url,
                    data:{
                        operator_id: operator_id,
                        occasion_id: occasion_id
                    },
                    success:function(result){
                        //console.log(result);
                        //change html of image select with the result images
                        $('#choosePicture').html(result);

                        //BUG: call image picker again
                        $('#choosePicture').imagepicker();
                    }
                });
            });//end change event



        });//end ready

    </script>
@stop