@extends('greeting.master')
@section('style')
    <style>
        #progressbar {
            width: 80%;
            margin: 15px auto 20px;
        }

        #progressbar li{
            width: 50%;
        }
    </style>
@stop
@section('form')
    <!--<form id="greetingForm">-->
    {!! Form::open(['id'=>'greetingForm','action'=>'FrontEndController@processImage','method' => 'get']) !!}
    <!-- progress bar -->

    <!--<ul id="progressbar" class="cf">
        <li class="active">المناسبة</li>
        <li>الاسم</li>
    </ul>-->

    <!-- fieldsets -->
        @if($errors->any())

            <div class="errors">
                <i class="fa fa-times"></i>
                <ul class="alert-box warning round">
                    @foreach($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    <fieldset id="picture">
        <div>
            <div class="fieldset-wrapper">
                {!! Form::label('occasion_id','اختر المناسبة') !!}

                <div class="select-panel">
                    {!! Form::select('occasion_id',$occasions,$default,['id'=>'chooseOccasion','data-url'=>url('images')]) !!}
                    <i class="fa fa-angle-down"></i>
                </div>

                <!-- hidden input for operator_id -->
                {!! Form::hidden('operator_id',$url->operator_id,['id'=>'operator_id'])!!}

                <!-- the options are generated by script-->
                {!! Form::label('choosePicture','اختر الصورة') !!}

                <div id="thumbnails-container" class="cf">

                    <select id="choosePicture" name="image" class="image-picker ajax-select">
                        @include('greeting._chooseImg')
                    </select>

                </div>
            </div>

            <div class="fieldset-controls">
                <input id="continue" type="hidden"  name="next" class="next action-button ajax-select no-float" value="استمرار" />

            </div>
        </div>


    </fieldset>


    <fieldset id="enterName">
        <div>
            <div class="fieldset-wrapper">
                <span class="input input--nariko">
                    <input required="required" class="input__field input__field--nariko" type="text" name="name" id="input-22" />
                    <label class="input__label input__label--nariko" for="input-22">
                      <span class="input__label-content input__label-content--nariko">النص </span>
                    </label>
                </span>
                
                <span class="input input--nariko">
                      <input type="submit" style="background: #3067AB !important;color:#fff;font-family: 'Droid Arabic Kufi', sans-serif !important ;" id="submit" data-img-src="{{asset('img/oval.svg')}}" class="" value="انتهاء"/>

                      </span>
                      
                      
            </div>

            <div class="fieldset-controls cf">
                <input  type="hidden" name="previous" class="previous action-button" value="رجوع" />
                <input  type="hidden"  data-img-src="{{asset('img/oval.svg')}}" class="submit" value="انتهاء"/>

            </div>
        </div>

    </fieldset>


    {!! Form::close()!!}
    <!--<div class="clearFooter"></div>-->
@stop
@section('script')
    <script>

        $(function(){
            /*
             *  select menu with image options
             */
            $('#choosePicture').imagepicker();

            /*
             *  onchange event on select occasion to load images for occasion
             */
            $('#chooseOccasion').on('change',function(){
                var occasion_id   = $(this).val();   // greetingImg->id
                var operator_id   = $('#operator_id').val();   // operator->id for current url 
                var url           = $(this).attr('data-url');    // ttp://localhost:8000/images   ---- current path url/images
               

                // send data with ajax
                $.ajax({
                    type:'GET',
                    url: url,
                    data:{
                        operator_id: operator_id,
                        occasion_id: occasion_id
                    },
                    success:function(result){
                        //console.log(result);
                        //change html of image select with the result images
                        $('#thumbnails-container').html(result);

                        //BUG: call image picker again  --- intalize 
                        $('#choosePicture').imagepicker();
                    }
                });
            });//end change event



        });//end ready

    </script>
@stop